---
title: "KNN"
author: "Nils Tinner"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
packages <- c("influxdbclient","ggplot2","tidyverse","lubridate","raster","dplyr","googledrive","caret","rgdal")

source("../R/load_packages.R")
load_packages(packages)

```

```{r}
  # You can generate an API token from the "API Tokens Tab" in the UI
  token = "tu3zUeCazQobS4TrIIRftQS3Tr4xoZQoZaRf0Ve0iCrU4LZSY1jTS3laCJ_OjwJxWJ6WsKuwXN_tVV10R73hyg=="

  client <- InfluxDBClient$new(url = "https://influx.smcs.abilium.io",
                               token = token,
                               org = "abilium")

  #reading tables
  tables <- client$query('from(bucket: "smcs") |> range(start: 2023-09-24) |> filter(fn: (r) => r["_measurement"] == "mqtt_consumer") |> filter(fn: (r) => r["_field"] == "decoded_payload_temperature" or r["_field"] == "decoded_payload_humidity") |> filter(fn: (r) => r["topic"] != "v3/dynamicventilation@ttn/devices/eui-f613c9feff19276a/up") |> filter(fn: (r) => r["topic"] != "helium/eeea9617559b/rx") |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")')

```

```{r}
  #getting time
  currenttime <- Sys.time()
  laggingtime <- currenttime - lubridate::minutes(30)


  #Setup for inital dataframe
  combined <- tibble(name = character(), temperature = double())
```



```{r}
  #adding of data to dataframe

# tables <- purrr::map(tables, ~mutate(.time = with_tz(.x$.time, tz = "Europe/Zurich")))
# tables <- purrr::map(tables,~filter(time > laggingtime)|>
#       group_by(topic)|>
#       summarise(temp = mean(decoded_payload_temperature)))
           
#Somehow not functional but would be prettier.. lets use this:

  for (x in 1:length(tables)) {
    tables[[x]]$time <- with_tz(tables[[x]]$time,"Europe/Zurich")
    temp <- tables[[x]] |>
      filter(time > laggingtime)|>
      group_by(topic)|>
      summarise(temp = mean(decoded_payload_temperature))

    combined <- combined |>
      add_row(name = temp$topic, temperature = temp$temp)
    #somewhow emtpy rows are dropped, nice ;)

  }

```




```{r}
  combined <- combined |>
    mutate(name = str_extract(name, "(?<=/)[^/]+(?=/)"))



  #reading in metadata
  meta <- read_csv("../data/Messnetz_2023_MODIFIED.csv")|>
    mutate(name = Code_grafana)


  #only take ours
  combined <- combined |>
    filter(name %in% meta$Code_grafana)


  #Attach meta information
  combined <- combined |>
    inner_join(meta, by = "name")





  tiff_names <- list.files("../data/Tiffs/")
  tiff_names_short <- tiff_names |>
    str_sub(end = -5)

```


```{r}
for (file in tiff_names) {
    # Read the TIF file
    raster_data <- raster::raster(paste("../data/Tiffs/",file,sep = ""))

    # Extract values at the points
    points_values <- raster::extract(raster_data, combined[, c("LV_03_E", "LV_03_N")])

    # Add the extracted values to the points_table
    combined[paste(str_sub(file,end = -5))] <- points_values
  }



```

```{r}
combined <- combined |>
    filter(complete.cases(across(all_of(tiff_names_short))))

  correlators <- tiff_names_short|>
    paste(collapse  = "+")

  formula_local = as.formula(paste("temperature","~", correlators))

  pp <- recipes::recipe(formula_local,
                        data = combined) |>
    recipes::step_center(recipes::all_numeric(), -recipes::all_outcomes()) |>
    recipes::step_scale(recipes::all_numeric(), -recipes::all_outcomes())

  mod_cv <- caret::train(pp,
                         data = combined,
                         method = "knn",
                         trControl = caret::trainControl(method = "cv"),
                         tuneGrid = data.frame(k = c(5,8,10,15,20,35,50,65)),
                         metric = "Rsquared")

```

```{r}
tiffs <-purrr::map(as.list(tiff_names_short),~raster::raster(paste("../data/Tiffs/",.,".tif",sep = "")))


# raster::intersect(tiffs)
# 
# extents <- lapply(tiffs, extent)
# 
# lapply(extents, min)
# min_extent <- do.call("min", extents)


# do.call(raster::intersect,tiffs)
# This should work but doesnt! 

#This works: but is very very ugly

common_extent <- extent(tiffs[[1]])

for (i in 2:length(tiffs)) {
  common_extent <- intersect(common_extent, extent(tiffs[[i]]))
}




  tiffs<- purrr::map(tiffs,~crop(., common_extent))


  stack_tiffs <- raster::stack(tiffs)

  temp <- raster::predict(stack_tiffs,mod_cv)
  
```

```{r}
 extent <- rgdal::readOGR("../data/Extent_Bern.shp")
  rivers <- rgdal::readOGR("../data/Aare.shp")
  color = colorRampPalette(c("blue","deepskyblue", "white","orange", "red"))(100)
  raster::plot(temp, col = color)
  sp::plot(extent, add = T)
  sp::plot(rivers, add = T)
  points(combined$LV_03_E,combined$LV_03_N , pch = 16, cex = 1)
  text(combined$LV_03_E, combined$LV_03_N, round(combined$temperature,1), pos = 3,cex = 0.7, adj = c(1, 1))
  title(paste("R^2 = ",round(max(mod_cv$results$Rsquared),2),", Mean Temp Logger = ",round(mean(combined$temperature),2),", Logger Count = ",length(combined$name),", K = ", mod_cv$bestTune), currenttime)
```

