---
title: "KNN"
author: "Nils Tinner"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
packages <- c("influxdbclient","ggplot2","tidyverse","lubridate","raster","dplyr","googledrive","caret","rgdal","keras","vip")

source("../R/load_packages.R")
load_packages(packages)

```














```{r}
meteoswiss <- read_csv2("../data/Meteoswiss/order_114596_data.txt")
meteoswiss_names <-meteoswiss|>
  dplyr::select(-stn,-time)|>
  colnames() 


  tiff_names <- list.files("../data/Tiffs/")
  tiff_names_short <- tiff_names |>
    str_sub(end = -5)

```



```{r}
combined <- read_csv("../data/Combined.csv")







combined <- combined |>
    filter(complete.cases(across(all_of(tiff_names_short)))) |>
    dplyr::select(all_of(c(tiff_names_short,meteoswiss_names)),temperature,hour,month,year,day,Log_Nr) |> drop_na()



combined_test <- combined |> filter(year == 2021)
combined_train <- combined |> filter(year %in% c(2019,2020,2022))



  correlators <- c(tiff_names_short,meteoswiss_names[-1],"hour","day","month")|>
    paste(collapse  = "+",sep = "+")

  formula_local = as.formula(paste("temperature","~", correlators))

  pp <- recipes::recipe(formula_local,
                        data = combined_train) |>
    recipes::step_center(recipes::all_numeric(), -recipes::all_outcomes()) |>
    recipes::step_scale(recipes::all_numeric(), -recipes::all_outcomes())

  mod_cv <- caret::train(
  pp, 
  data = combined_train,
  method = "ranger",
  metric = "RMSE",
  trControl = trainControl(
    method = "cv",
    number = 5,
    savePredictions = "final"
    ),
  tuneGrid = expand.grid(
    .mtry = floor(73 / 3),       # default p/3
    .min.node.size = 10,         # set to 10
    .splitrule = "variance"     # default variance
    ),
  # arguments specific to "ranger" method
  replace = FALSE,
  sample.fraction = 0.5,
  num.trees = 100,       
  seed = 1982
)

  

  combined_test$fitted <- predict(mod_cv, newdata = combined_test)
  metrics_test <- combined_test |> 
    yardstick::metrics(temperature, fitted)
  
  combined_test<- combined_test|>mutate(difference = fitted-temperature)
  
```
Idea for better performance: when Log_Nr is added = better, because. some bias etc... Maybe add meteoswiss temp as own row then use the meteoswiss "logger" to generalise... Would that work?
```{r}
 rmse_test <- metrics_test |> 
    filter(.metric == "rmse") |> 
    pull(.estimate)
  rsq_test <- metrics_test |> 
    filter(.metric == "rsq") |> 
    pull(.estimate)
  
  
  vip::vip(mod_cv,                        # Model to use
         train = mod_cv$trainingData,   # Training data used in the model
         method = "permute",            # VIP method
         target = "temperature",     # Target variable
         nsim = 2,                      # Number of simulations
         metric = "RMSE",               # Metric to assess quantify permutation
         sample_frac = 0.1,             # Fraction of training data to use
         pred_wrapper = predict ,
         num_features = 15L# Prediction function to use
         )
  
  
ggplot(data = combined_test, aes(temperature, fitted)) +
    geom_point(alpha = 0.3) +
    geom_smooth(method = "lm", se = FALSE, color = "red") +
    geom_abline(slope = 1, intercept = 0, linetype = "dotted") +
    labs(subtitle = bquote( italic(R)^2 == .(format(rsq_test, digits = 2)) ~~
                            RMSE == .(format(rmse_test, digits = 3))),
         title = "Test set") +
    theme_classic()

# 
# 
# ggplot(
#     data = combined_test,
#     aes(x = temperature, y = fitted)) +
#   stat_density_2d(
#     geom = "raster", # the geometric object to display the data
#     aes(fill = after_stat(density)), # using `density`, a variable calculated by the stat
#     contour = FALSE 
#     ) +
#   scale_fill_viridis_c() +
#   labs(x = expression(paste("Shortwave radiation (W m"^-2, ")")), 
#        y = expression(paste("GPP (", mu,"mol CO"[2], " m"^-2, "s"^-1, ")")) ) +
#   theme_classic() + 
#   scale_x_continuous(expand = c(0, 0)) +  # avoid gap between plotting area and axis
#   scale_y_continuous(expand = c(0, 0))

  ggplot(data = combined_test,
         aes(x = as.factor(Log_Nr), y = abs(difference)))+
    geom_boxplot()
  # 
    ggplot(data = combined,
         aes(x = as.factor(Log_Nr), y = tre200s0-temperature))+
    geom_boxplot()

```


```{r}
tiffs <-purrr::map(as.list(tiff_names_short),~raster::raster(paste("../data/Tiffs/",.,".tif",sep = "")))


# raster::intersect(tiffs)
# 
# extents <- lapply(tiffs, extent)
# 
# lapply(extents, min)
# min_extent <- do.call("min", extents)


# do.call(raster::intersect,tiffs)
# purrr::map(tiffs,~intersect(.))
# These should work but doesnt! 

#This works: but is very very ugly

common_extent <- extent(tiffs[[1]])

for (i in 2:length(tiffs)) {
  common_extent <- intersect(common_extent, extent(tiffs[[i]]))
}





  tiffs<- purrr::map(tiffs,~crop(., common_extent))

# Goes:"gre000z0" "prestas0" "tre200s0" "rre150z0" "ure200s0" "fkl010z0" "dkl010z0"
#which is Globalstrahlung, Luftdruck, Lufttemperatur, Niederschlag, Relative Luftfeuchtigkeit, Windgeschwindigkeit, Windrichtung


meteo_pred <- c(0,9500,22.8,0.0,600,2.3,206,12,8,22)
names(meteo_pred) <- c(meteoswiss_names[-1],"day","month","hour")

meteo_pred <- c(1000,9559,25,0.0,600,2.3,206,12,8,14)
names(meteo_pred) <- c(meteoswiss_names[-1],"day","month","hour")


meteo_raster <- list()  
for (name in c(meteoswiss_names[-1],"day","month","hour")) {
  meteo_raster[[name]] <- raster(ncol=293, nrow=247, xmn=2592670, xmx=2607320, ymn=1193202, ymx=1205552)
raster::values(meteo_raster[[name]]) <- unname(meteo_pred[name])
meteo_raster[[name]] <- crop(meteo_raster[[name]],common_extent)

}
  



  stack_tiffs <- raster::stack(tiffs)
  stack_meteo <- raster::stack(meteo_raster)
  stack <- raster::stack(stack_meteo,stack_tiffs)
  temperature <- raster::predict(stack,mod_cv)
  
```



```{r}
 extent <- rgdal::readOGR("../data/Map/Extent_Bern.shp")
  rivers <- rgdal::readOGR("../data/Map/Aare.shp")
  color = colorRampPalette(c("blue","deepskyblue", "white","orange", "red"))(100)
  raster::plot(temperature, col = color)
  sp::plot(extent, add = T)
  sp::plot(rivers, add = T)
  points( 2601930.3,1204410.1 , pch = 16, cex = 1)


```
