---
title: 'Linear Regression Model'
author: "Patrick Bigler, Nils Tinner"
date: "2023-04-03"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
  '': default
editor_options:
  markdown:
    wrap: 75
---

We load the packages

```{r Packages,  error=FALSE, message=FALSE, warning=FALSE}}
packages <- c("influxdbclient","ggplot2","tidyverse","lubridate","raster","dplyr","googledrive","caret","rgdal","keras")

source("../../AGDS_Bigler_Tinner/R/load_packages.R")
load_packages(packages)

source("../R/packages.R")
```

We load the the file (there are no packages in the R-script! you have to
load it first!)

```{r create_or_read_Combined, error=FALSE, message=FALSE, warning=FALSE}
# We are looking for a certain file
name.of.file <- '../data/Combined.csv'

if (!file.exists(name.of.file)){
  # If there is no such file, we load a function which will create the file
  source('../R/function_to_create_Combined.R')
  Combined <- looking_for_Combined.csv()
}else{
  # If there is such a file, we read it
  Combined <- read_csv("../data/Combined.csv")
}

# We want to see the first few rows to ensure that everything is alright
kableExtra::kable(head(Combined))|>
  kableExtra::kable_classic()

```

We create a stepwise regression and visualize it

```{r stepwise_regression, error=FALSE, message=FALSE, warning=FALSE}
source('../R/stepwise/stepforward.R')

multi.model <- multivariate.reg.model(Combined, c(1, 2, 4, 5, 13, 14, 15, 16, 17))

source("../R/function.vis.stepwise.R")

p1 <- vis.and.dev.multi.model(multi.model)
p1

```

```{r multivariate_regression, error=FALSE, message=FALSE, warning=FALSE}

# Calculate the probably best multivariate model
multi.lm <- lm(temperature ~ tre200s0 + gre000z0 + ure200s0 + BUL_250 + 
                      dkl010z0 + prestas0 + VH_150 + AC_750 + rre150z0 + HuM + TPI_500 +
                 GA_25 + FO_1000 + WA_150 + SLO_50 + fkl010z0, 
                    data = Combined)

# Shows the residues
plot(multi.lm)

# Shows all the parameters
summary(multi.lm)
```
