---
title: "main"
author: "Nils Tinner, Patrick Bigler"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
  '': default
editor_options:
  markdown:
    wrap: 75
---


## Preparation

```{r}
packages <- c("influxdbclient","ggplot2","tidyverse","lubridate","raster",
              "dplyr","googledrive","caret","rgdal","keras","vip","parsnip","workflows","tune","dials","stringr","terra","stars","sf")

source("../R/load_packages.R")
load_packages(packages)

```

## Data Wrangling
```{r message=FALSE, warning=FALSE}

source("../R/raw_tif_processing.R")


source("../R/data_combination.R")
#here add check, if present load if not run function
combined <- data_combination() |> drop_na() #not very clean but okay
combined <- read_csv("../data/Combined.csv") |> 
  mutate(temperature = temperature-temp) |>
  drop_na()

set.seed(123)
loggers_test <- sample(unique(combined$Log_Nr), 10)

combined_test <- combined |> 
  filter((Log_Nr %in% loggers_test))
combined_train <- combined |> 
  filter(!(Log_Nr %in% loggers_test))

```


Model Definitions
```{r}
#Old Version

# predictors <- combined |>
#   dplyr::select(-c(Log_Nr,temperature,Name,NORD_CHTOP,OST_CHTOPO)) |>
#   colnames()
#   formula_local <- as.formula(paste("temperature","~", paste(predictors,collapse  = "+")))
#   
# 
#   pp <- recipes::recipe(formula_local,
#                         data = combined_train) |>
#     recipes::step_center(recipes::all_numeric(), -recipes::all_outcomes()) |>
#     recipes::step_scale(recipes::all_numeric(), -recipes::all_outcomes())
#   

  

predictors <- combined |>
  dplyr::select(c(hour,day,month,temp,rad,rain,rain1,temp_3,temp_5,rain1,rain2,
                  rain3,SE_Raster_101,FO_Raster_51,GA_Raster_5,WA_Raster_21,
                  AC_Raster_101,SLO_21,VH_WSL_21_21,SVF_5,Bul_Raster_51,BH_21,DEM,LV_03_E,LV_03_N)) |>
  colnames()
  formula_local <- as.formula(paste("temperature","~", paste(predictors,collapse  = "+")))
  

pp <- recipes::recipe(formula_local,
                      data = combined_train) |>
    recipes::step_BoxCox(recipes::all_predictors()) |>
    recipes::step_center(recipes::all_numeric(), -recipes::all_outcomes()) |>
    recipes::step_scale(recipes::all_numeric(), -recipes::all_outcomes())

```




Model Training
```{r}
source("../R/random_forest.R")
random_forest_model <- random_forest(pp,combined_train)

```


Evaluation
```{r}
source("../R/evaluation.R")
eval <- evaluate(combined_test,random_forest_model)
eval[[1]]
eval[[2]]





```


```{r}

source("../R/XGB.R")
# type of task we want to evaluate
model_settings <- parsnip::boost_tree(
  trees = tune(),
  min_n = tune(),
  tree_depth = tune(),
  learn_rate = tune(),
  loss_reduction = tune(),
  stop_iter = 20,
) |>
  set_engine("xgboost",nthread = 6, verbose = T) |>
  set_mode("regression")
xgb_workflow <- workflows::workflow() |>
  add_formula(temperature ~ .) |>
  add_model(model_settings)

combined_train_xgb <- combined_train |> dplyr::select(temperature,hour,day,month,temp,rad,rain,rain1,temp_3,temp_5,rain1,rain2,
                  rain3,SE_Raster_101,FO_Raster_51,GA_Raster_5,WA_Raster_21,
                  AC_Raster_101,SLO_21,VH_WSL_21_21,SVF_5,Bul_Raster_51,BH_21,DEM,LV_03_E,LV_03_N)

xgb_results <- xgb(xgb_workflow,train = combined_train_xgb)



# select the best model based upon
# the root mean squared error
xgb_best <- tune::select_best(
  xgb_results,
  metric = "rmse"
)

# cook up a model using finalize_workflow
# which takes workflow (model) specifications
# and combines it with optimal model
# parameters into a model workflow
xgb_best_hp <- tune::finalize_workflow(
  xgb_workflow,
  xgb_best
)



combined_test_xgb <- combined_test|> dplyr::select(c(temperature,hour,day,month,temp,rad,rain,rain1,temp_3,temp_5,rain1,rain2,
                  rain3,SE_Raster_101,FO_Raster_51,GA_Raster_5,WA_Raster_21,
                  AC_Raster_101,SLO_21,VH_WSL_21_21,SVF_5,Bul_Raster_51,BH_21,DEM,LV_03_E,LV_03_N))


# train a final (best) model with optimal
# hyper-parameters
xgb_best_model <- fit(xgb_best_hp, combined_train_xgb)


source("../R/evaluation.R")
eval <- evaluate(combined_test_xgb,xgb_best_model)
 eval[[1]]
 eval[[2]]

```


