---
title: "Random Forest"
author: "Nils Tinner"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
packages <- c("influxdbclient","ggplot2","tidyverse","lubridate","raster","dplyr","googledrive","caret","rgdal","keras","vip")

source("../R/load_packages.R")
load_packages(packages)

```














```{r}
meteoswiss <- read_csv2("../data/Meteoswiss/order_114596_data.txt")
meteoswiss_names <-meteoswiss|>
  dplyr::select(-stn,-time)|>
  colnames() 


  tiff_names <- list.files("../data/Tiffs/")
  tiff_names_short <- tiff_names |>
    str_sub(end = -5)

```



```{r}
combined <- read_csv("../data/Combined.csv")







combined <- combined |>
    filter(complete.cases(across(all_of(tiff_names_short)))) |>
    dplyr::select(all_of(c(tiff_names_short,meteoswiss_names)),temperature,hour,month,year,day,Log_Nr) |> drop_na()



combined_test <- combined |> filter(year == 2021) |>
  filter((Log_Nr %in% c(82,45)))
combined_train <- combined |> filter(year %in% c(2019,2020,2022)) |>
  filter(!(Log_Nr %in% c(82,45)))



  correlators <- c(tiff_names_short,meteoswiss_names[-1],"hour","day","month")|>
    paste(collapse  = "+",sep = "+")

  formula_local = as.formula(paste("temperature","~", correlators))

  pp <- recipes::recipe(formula_local,
                        data = combined_train) |>
    recipes::step_center(recipes::all_numeric(), -recipes::all_outcomes()) |>
    recipes::step_scale(recipes::all_numeric(), -recipes::all_outcomes())

  mod_cv <- caret::train(
  pp, 
  data = combined_train,
  method = "ranger",
  metric = "RMSE",
  trControl = trainControl(
    method = "cv",
    number = 5,
    savePredictions = "final"
    ),
  tuneGrid = expand.grid(
    .mtry = 35,       # default p/3
    .min.node.size = 2,         # set to 5
    .splitrule = "variance"     # default variance
    ),
  # arguments specific to "ranger" method
  replace = FALSE,
  sample.fraction = 0.5,
  num.trees = 10,       
  seed = 1982
)

  

  combined_test$fitted <- predict(mod_cv, newdata = combined_test)
  metrics_test <- combined_test |> 
    yardstick::metrics(temperature, fitted)
  
  combined_test<- combined_test|>mutate(difference = fitted-temperature)
  
```
Idea for better performance: when Log_Nr is added = better, because. some bias etc... Maybe add meteoswiss temp as own row then use the meteoswiss "logger" to generalise... Would that work?
```{r}
 rmse_test <- metrics_test |> 
    filter(.metric == "rmse") |> 
    pull(.estimate)
  rsq_test <- metrics_test |> 
    filter(.metric == "rsq") |> 
    pull(.estimate)
  
  
  # vip::vip(mod_cv,                        # Model to use
  #        train = mod_cv$trainingData,   # Training data used in the model
  #        method = "permute",            # VIP method
  #        target = "temperature",     # Target variable
  #        nsim = 1,                      # Number of simulations
  #        metric = "RMSE",               # Metric to assess quantify permutation
  #        sample_frac = 0.1,             # Fraction of training data to use
  #        pred_wrapper = predict ,
  #        num_features = 20L# Prediction function to use
  #        )
  
  
ggplot(data = combined_test, aes(temperature, fitted)) +
    geom_point(alpha = 0.3) +
    geom_smooth(method = "lm", se = FALSE, color = "red") +
    geom_abline(slope = 1, intercept = 0, linetype = "dotted") +
    labs(subtitle = bquote( italic(R)^2 == .(format(rsq_test, digits = 2)) ~~
                            RMSE == .(format(rmse_test, digits = 3))),
         title = "Test set") +
    theme_classic()



  ggplot(data = combined_test,
         aes(x = as.factor(Log_Nr), y = abs(difference)))+
    geom_boxplot()


  ggplot(data = combined_test,
         aes(x = as.factor(hour), y = abs(difference)))+
    geom_boxplot()
    
```


```{r}


tiffs <- list()
for (tif in tiff_names_short) {
  tiffs[tif] = terra::rast(paste("../data/Tiffs/",tif,".tif",sep = ""))
  terra::set.names(tiffs[[tif]],tif)
}



# Goes:"gre000z0" "prestas0" "tre200s0" "rre150z0" "ure200s0" "fkl010z0" "dkl010z0"
#which is Globalstrahlung, Luftdruck, Lufttemperatur, Niederschlag, Relative Luftfeuchtigkeit, Windgeschwindigkeit, Windrichtung



meteo_pred <- c(1000,9559,25,0.0,600,2.3,206,12,8,14)
names(meteo_pred) <- c(meteoswiss_names[-1],"day","month","hour")



for (name in c(meteoswiss_names[-1],"day","month","hour")) {
  tiffs[[name]] <- terra::rast(ncol=293, nrow=247, xmin=2592670, xmax=2607320, ymin=1193202, ymax=1205552,names = name)
terra::values(tiffs[[name]]) <- unname(meteo_pred[name])

}




 minimal_extent <- terra::ext(tiffs[[1]])

# Loop through the list of raster paths to find the minimal extent
for (tif in tiffs) {
    raster_extent <- terra::ext(tif)
    minimal_extent <- terra::intersect(minimal_extent, raster_extent)
}
cropped <- terra::crop(tiffs[[1]],minimal_extent)


for (x in 2:length(tiffs)) {
tiffs[[x]]<- terra::crop(tiffs[[x]],minimal_extent)
}

tiffs_stack <- tiffs[[1]]

 for (x in 2:length(tiffs)) {
  tiffs_stack <- c(tiffs_stack,tiffs[[x]])
}

  temperature <- terra::predict(tiffs_stack,mod_cv,na.rm = T)
  
```



```{r}
 extent <- rgdal::readOGR("../data/Map/Extent_Bern.shp")
  rivers <- rgdal::readOGR("../data/Map/Aare.shp")
  color = colorRampPalette(c("blue","deepskyblue", "white","orange", "red"))(100)
  raster::plot(temperature, col = color)
  sp::plot(extent, add = T)
  sp::plot(rivers, add = T)
  points( 2601930.3,1204410.1 , pch = 16, cex = 1)


```
